In [1]:
from datasets import load_dataset

In [2]:
import pandas as pd

In [3]:
dataset=load_dataset("MongoDB/embedded_movies")

In [4]:
data=pd.DataFrame(dataset["train"])

In [5]:
data

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,plot_embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.0007293965299999999, -0.026834568000000003,..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.022837115, -0.022941574000000003, 0.014937..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.00023330492999999998, -0.028511643000000003..."
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.005927917, -0.033394486, 0.0015323418, -0...."
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0059373598, -0.026604708, -0.0070914757000..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,"In the ironically named city of Paradise, a re...",100.0,"[Action, Comedy, Thriller]",The story begins with a regular Joe who tries ...,[Uwe Boll],"[Uwe Boll, Bryan C. Knight]","[USA, Canada, Germany]",https://m.media-amazon.com/images/M/MV5BMTIzMD...,[English],"[Zack Ward, Dave Foley, Chris Coppola, Jackie ...",Postal,0,R,"{'id': 486640, 'rating': 4.4, 'votes': 19641}","{'nominations': 3, 'text': '1 win & 3 nominati...",movie,22.0,"[-0.0121000735, -0.041997142, -0.005094945, -0..."
1496,A group of suburban biker wannabes looking for...,100.0,"[Action, Adventure, Comedy]",Four middle-aged men decide to take a road tri...,[Walt Becker],[Brad Copeland],[USA],https://m.media-amazon.com/images/M/MV5BZWZlMz...,[English],"[Tim Allen, John Travolta, Martin Lawrence, Wi...",Wild Hogs,0,PG-13,"{'id': 486946, 'rating': 5.9, 'votes': 94699}","{'nominations': 3, 'text': '3 nominations.', '...",movie,27.0,"[-0.0070759640000000006, -0.021997746000000002..."
1497,"Shakespeare's masterpiece ""Othello"" set in mod...",155.0,"[Action, Crime, Drama]",Advocate Raghunath Mishra has arranged the mar...,[Vishal Bhardwaj],"[Vishal Bhardwaj (screenplay), Robin Bhatt (sc...",[India],https://m.media-amazon.com/images/M/MV5BY2NmNj...,[Hindi],"[Ajay Devgn, Kareena Kapoor, Saif Ali Khan, Ko...",Omkara,1,None,"{'id': 488414, 'rating': 8.2, 'votes': 9800}","{'nominations': 13, 'text': '14 wins & 13 nomi...",movie,NaN,"[-0.010883339, -0.016018711, -0.00972983500000..."
1498,When a small Colorado town is overrun by the f...,86.0,"[Action, Horror]","In Leadville, Colorado, Captain Rhodes and his...",[Steve Miner],"[Jeffrey Reddick (screenplay), George A. Romer...",[USA],https://m.media-amazon.com/images/M/MV5BNzg1Mj...,[English],"[Mena Suvari, Nick Cannon, Michael Welch, Anna...",Day of the Dead,1,R,"{'id': 489018, 'rating': 4.5, 'votes': 17177}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[0.008735137, -0.010910851000000001, 0.0005507..."
1499,A teenager with teleportation abilities sudden...,88.0,"[Action, Adventure, Sci-Fi]",David Rice is a high school student in Ann Arb...,[Doug Liman],"[David S. Goyer (screenplay), Jim Uhls (screen...","[USA, Canada]",https://m.media-amazon.com/images/M/MV5BMjEwOT...,"[English, Italian, Japanese, Mandarin]","[Hayden Christensen, Jamie Bell, Rachel Bilson...",Jumper,0,PG-13,"{'id': 489099, 'rating': 6.1, 'votes': 226607}","{'nominations': 4, 'text': '2 wins & 4 nominat...",movie,35.0,"[0.010128586, -0.028155368, -0.0051364526, -0...."

In [6]:
data.columns

Index(['plot', 'runtime', 'genres', 'fullplot', 'directors', 'writers',
       'countries', 'poster', 'languages', 'cast', 'title',
       'num_mflix_comments', 'rated', 'imdb', 'awards', 'type', 'metacritic',
       'plot_embedding'],
      dtype='object')

In [7]:
data.isnull().sum()

plot                   27
runtime                15
genres                  0
fullplot               48
directors              13
writers                13
countries               0
poster                 89
languages               1
cast                    1
title                   0
num_mflix_comments      0
rated                 308
imdb                    0
awards                  0
type                    0
metacritic            928
plot_embedding         28
dtype: int64

In [8]:
data.isnull().sum().sum()

1471

In [9]:
data=data.dropna(subset=["fullplot"])

In [10]:
data

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,plot_embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.0007293965299999999, -0.026834568000000003,..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.022837115, -0.022941574000000003, 0.014937..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.00023330492999999998, -0.028511643000000003..."
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.005927917, -0.033394486, 0.0015323418, -0...."
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0059373598, -0.026604708, -0.0070914757000..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,"In the ironically named city of Paradise, a re...",100.0,"[Action, Comedy, Thriller]",The story begins with a regular Joe who tries ...,[Uwe Boll],"[Uwe Boll, Bryan C. Knight]","[USA, Canada, Germany]",https://m.media-amazon.com/images/M/MV5BMTIzMD...,[English],"[Zack Ward, Dave Foley, Chris Coppola, Jackie ...",Postal,0,R,"{'id': 486640, 'rating': 4.4, 'votes': 19641}","{'nominations': 3, 'text': '1 win & 3 nominati...",movie,22.0,"[-0.0121000735, -0.041997142, -0.005094945, -0..."
1496,A group of suburban biker wannabes looking for...,100.0,"[Action, Adventure, Comedy]",Four middle-aged men decide to take a road tri...,[Walt Becker],[Brad Copeland],[USA],https://m.media-amazon.com/images/M/MV5BZWZlMz...,[English],"[Tim Allen, John Travolta, Martin Lawrence, Wi...",Wild Hogs,0,PG-13,"{'id': 486946, 'rating': 5.9, 'votes': 94699}","{'nominations': 3, 'text': '3 nominations.', '...",movie,27.0,"[-0.0070759640000000006, -0.021997746000000002..."
1497,"Shakespeare's masterpiece ""Othello"" set in mod...",155.0,"[Action, Crime, Drama]",Advocate Raghunath Mishra has arranged the mar...,[Vishal Bhardwaj],"[Vishal Bhardwaj (screenplay), Robin Bhatt (sc...",[India],https://m.media-amazon.com/images/M/MV5BY2NmNj...,[Hindi],"[Ajay Devgn, Kareena Kapoor, Saif Ali Khan, Ko...",Omkara,1,None,"{'id': 488414, 'rating': 8.2, 'votes': 9800}","{'nominations': 13, 'text': '14 wins & 13 nomi...",movie,NaN,"[-0.010883339, -0.016018711, -0.00972983500000..."
1498,When a small Colorado town is overrun by the f...,86.0,"[Action, Horror]","In Leadville, Colorado, Captain Rhodes and his...",[Steve Miner],"[Jeffrey Reddick (screenplay), George A. Romer...",[USA],https://m.media-amazon.com/images/M/MV5BNzg1Mj...,[English],"[Mena Suvari, Nick Cannon, Michael Welch, Anna...",Day of the Dead,1,R,"{'id': 489018, 'rating': 4.5, 'votes': 17177}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[0.008735137, -0.010910851000000001, 0.0005507..."
1499,A teenager with teleportation abilities sudden...,88.0,"[Action, Adventure, Sci-Fi]",David Rice is a high school student in Ann Arb...,[Doug Liman],"[David S. Goyer (screenplay), Jim Uhls (screen...","[USA, Canada]",https://m.media-amazon.com/images/M/MV5BMjEwOT...,"[English, Italian, Japanese, Mandarin]","[Hayden Christensen, Jamie Bell, Rachel Bilson...",Jumper,0,PG-13,"{'id': 489099, 'rating': 6.1, 'votes': 226607}","{'nominations': 4, 'text': '2 wins & 4 nominat...",movie,35.0,"[0.010128586, -0.028155368, -0.0051364526, -0...."

In [11]:
data=data.drop(columns=["plot_embedding"])

In [12]:
data.head()

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN

In [13]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer("thenlper/gte-large")

In [14]:
def get_embedding(text:str)->list[float]:

    if not text.strip():
        print("attempted to get embedding for empty text.")
        return []
    
    embedding=embedding_model.encode(text)
    return embedding.tolist()

In [16]:
data["embeding"]=data["fullplot"].apply(get_embedding)

In [17]:
import pymongo

In [18]:

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://1234:1234@cluster0.intku.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [19]:
db=client["mongorag"]

In [20]:
collection=db["mongoragcollection"]

In [21]:
'''collection.insert_one({
    "name":"muskan",
    "age":25,
    "city":"chandigarh"
})'''

'collection.insert_one({\n    "name":"muskan",\n    "age":25,\n    "city":"chandigarh"\n})'

In [22]:
documents=data.to_dict("records")

In [23]:
collection.insert_many(documents)

InsertManyResult([ObjectId('67d93b1b80ba3433e7194e6f'), ObjectId('67d93b1b80ba3433e7194e70'), ObjectId('67d93b1b80ba3433e7194e71'), ObjectId('67d93b1b80ba3433e7194e72'), ObjectId('67d93b1b80ba3433e7194e73'), ObjectId('67d93b1b80ba3433e7194e74'), ObjectId('67d93b1b80ba3433e7194e75'), ObjectId('67d93b1b80ba3433e7194e76'), ObjectId('67d93b1b80ba3433e7194e77'), ObjectId('67d93b1b80ba3433e7194e78'), ObjectId('67d93b1b80ba3433e7194e79'), ObjectId('67d93b1b80ba3433e7194e7a'), ObjectId('67d93b1b80ba3433e7194e7b'), ObjectId('67d93b1b80ba3433e7194e7c'), ObjectId('67d93b1b80ba3433e7194e7d'), ObjectId('67d93b1b80ba3433e7194e7e'), ObjectId('67d93b1b80ba3433e7194e7f'), ObjectId('67d93b1b80ba3433e7194e80'), ObjectId('67d93b1b80ba3433e7194e81'), ObjectId('67d93b1b80ba3433e7194e82'), ObjectId('67d93b1b80ba3433e7194e83'), ObjectId('67d93b1b80ba3433e7194e84'), ObjectId('67d93b1b80ba3433e7194e85'), ObjectId('67d93b1b80ba3433e7194e86'), ObjectId('67d93b1b80ba3433e7194e87'), ObjectId('67d93b1b80ba3433e7194e88'), ObjectId('67d93b1b80ba3433e7194e89'), ObjectId('67d93b1b80ba3433e7194e8a'), ObjectId('67d93b1b80ba3433e7194e8b'), ObjectId('67d93b1b80ba3433e7194e8c'), ObjectId('67d93b1b80ba3433e7194e8d'), ObjectId('67d93b1b80ba3433e7194e8e'), ObjectId('67d93b1b80ba3433e7194e8f'), ObjectId('67d93b1b80ba3433e7194e90'), ObjectId('67d93b1b80ba3433e7194e91'), ObjectId('67d93b1b80ba3433e7194e92'), ObjectId('67d93b1b80ba3433e7194e93'), ObjectId('67d93b1b80ba3433e7194e94'), ObjectId('67d93b1b80ba3433e7194e95'), ObjectId('67d93b1b80ba3433e7194e96'), ObjectId('67d93b1b80ba3433e7194e97'), ObjectId('67d93b1b80ba3433e7194e98'), ObjectId('67d93b1b80ba3433e7194e99'), ObjectId('67d93b1b80ba3433e7194e9a'), ObjectId('67d93b1b80ba3433e7194e9b'), ObjectId('67d93b1b80ba3433e7194e9c'), ObjectId('67d93b1b80ba3433e7194e9d'), ObjectId('67d93b1b80ba3433e7194e9e'), ObjectId('67d93b1b80ba3433e7194e9f'), ObjectId('67d93b1b80ba3433e7194ea0'), ObjectId('67d93b1b80ba3433e7194ea1'), ObjectId('67d93b1b80ba3433e7194ea2'), ObjectId('67d93b1b80ba3433e7194ea3'), ObjectId('67d93b1b80ba3433e7194ea4'), ObjectId('67d93b1b80ba3433e7194ea5'), ObjectId('67d93b1b80ba3433e7194ea6'), ObjectId('67d93b1b80ba3433e7194ea7'), ObjectId('67d93b1b80ba3433e7194ea8'), ObjectId('67d93b1b80ba3433e7194ea9'), ObjectId('67d93b1b80ba3433e7194eaa'), ObjectId('67d93b1b80ba3433e7194eab'), ObjectId('67d93b1b80ba3433e7194eac'), ObjectId('67d93b1b80ba3433e7194ead'), ObjectId('67d93b1b80ba3433e7194eae'), ObjectId('67d93b1b80ba3433e7194eaf'), ObjectId('67d93b1b80ba3433e7194eb0'), ObjectId('67d93b1b80ba3433e7194eb1'), ObjectId('67d93b1b80ba3433e7194eb2'), ObjectId('67d93b1b80ba3433e7194eb3'), ObjectId('67d93b1b80ba3433e7194eb4'), ObjectId('67d93b1b80ba3433e7194eb5'), ObjectId('67d93b1b80ba3433e7194eb6'), ObjectId('67d93b1b80ba3433e7194eb7'), ObjectId('67d93b1b80ba3433e7194eb8'), ObjectId('67d93b1b80ba3433e7194eb9'), ObjectId('67d93b1b80ba3433e7194eba'), ObjectId('67d93b1b80ba3433e7194ebb'), ObjectId('67d93b1b80ba3433e7194ebc'), ObjectId('67d93b1b80ba3433e7194ebd'), ObjectId('67d93b1b80ba3433e7194ebe'), ObjectId('67d93b1b80ba3433e7194ebf'), ObjectId('67d93b1b80ba3433e7194ec0'), ObjectId('67d93b1b80ba3433e7194ec1'), ObjectId('67d93b1b80ba3433e7194ec2'), ObjectId('67d93b1b80ba3433e7194ec3'), ObjectId('67d93b1b80ba3433e7194ec4'), ObjectId('67d93b1b80ba3433e7194ec5'), ObjectId('67d93b1b80ba3433e7194ec6'), ObjectId('67d93b1b80ba3433e7194ec7'), ObjectId('67d93b1b80ba3433e7194ec8'), ObjectId('67d93b1b80ba3433e7194ec9'), ObjectId('67d93b1b80ba3433e7194eca'), ObjectId('67d93b1b80ba3433e7194ecb'), ObjectId('67d93b1b80ba3433e7194ecc'), ObjectId('67d93b1b80ba3433e7194ecd'), ObjectId('67d93b1b80ba3433e7194ece'), ObjectId('67d93b1b80ba3433e7194ecf'), ObjectId('67d93b1b80ba3433e7194ed0'), ObjectId('67d93b1b80ba3433e7194ed1'), ObjectId('67d93b1b80ba3433e7194ed2'), ObjectId('67d93b1b80ba3433e7194ed3'), ObjectId('67d93b1b80ba3433e7194ed4'), ObjectId('67d93b1b80ba3433e7194ed5'), ObjectId('67d93b1b80ba3433e7194ed6'), ObjectId('67d93b1b80ba3433e7194ed7'), ObjectId('67d93b1b80ba3433e7194ed8'), ObjectId('67d93b1b80ba3433e7194ed9'), ObjectId('67d93b1b80ba3433e7194eda'), ObjectId('67d93b1b80ba3433e7194edb'), ObjectId('67d93b1b80ba3433e7194edc'), ObjectId('67d93b1b80ba3433e7194edd'), ObjectId('67d93b1b80ba3433e7194ede'), ObjectId('67d93b1b80ba3433e7194edf'), ObjectId('67d93b1b80ba3433e7194ee0'), ObjectId('67d93b1b80ba3433e7194ee1'), ObjectId('67d93b1b80ba3433e7194ee2'), ObjectId('67d93b1b80ba3433e7194ee3'), ObjectId('67d93b1b80ba3433e7194ee4'), ObjectId('67d93b1b80ba3433e7194ee5'), ObjectId('67d93b1b80ba3433e7194ee6'), ObjectId('67d93b1b80ba3433e7194ee7'), ObjectId('67d93b1b80ba3433e7194ee8'), ObjectId('67d93b1b80ba3433e7194ee9'), ObjectId('67d93b1b80ba3433e7194eea'), ObjectId('67d93b1b80ba3433e7194eeb'), ObjectId('67d93b1b80ba3433e7194eec'), ObjectId('67d93b1b80ba3433e7194eed'), ObjectId('67d93b1b80ba3433e7194eee'), ObjectId('67d93b1b80ba3433e7194eef'), ObjectId('67d93b1b80ba3433e7194ef0'), ObjectId('67d93b1b80ba3433e7194ef1'), ObjectId('67d93b1b80ba3433e7194ef2'), ObjectId('67d93b1b80ba3433e7194ef3'), ObjectId('67d93b1b80ba3433e7194ef4'), ObjectId('67d93b1b80ba3433e7194ef5'), ObjectId('67d93b1b80ba3433e7194ef6'), ObjectId('67d93b1b80ba3433e7194ef7'), ObjectId('67d93b1b80ba3433e7194ef8'), ObjectId('67d93b1b80ba3433e7194ef9'), ObjectId('67d93b1b80ba3433e7194efa'), ObjectId('67d93b1b80ba3433e7194efb'), ObjectId('67d93b1b80ba3433e7194efc'), ObjectId('67d93b1b80ba3433e7194efd'), ObjectId('67d93b1b80ba3433e7194efe'), ObjectId('67d93b1b80ba3433e7194eff'), ObjectId('67d93b1b80ba3433e7194f00'), ObjectId('67d93b1b80ba3433e7194f01'), ObjectId('67d93b1b80ba3433e7194f02'), ObjectId('67d93b1b80ba3433e7194f03'), ObjectId('67d93b1b80ba3433e7194f04'), ObjectId('67d93b1b80ba3433e7194f05'), ObjectId('67d93b1b80ba3433e7194f06'), ObjectId('67d93b1b80ba3433e7194f07'), ObjectId('67d93b1b80ba3433e7194f08'), ObjectId('67d93b1b80ba3433e7194f09'), ObjectId('67d93b1b80ba3433e7194f0a'), ObjectId('67d93b1b80ba3433e7194f0b'), ObjectId('67d93b1b80ba3433e7194f0c'), ObjectId('67d93b1b80ba3433e7194f0d'), ObjectId('67d93b1b80ba3433e7194f0e'), ObjectId('67d93b1b80ba3433e7194f0f'), ObjectId('67d93b1b80ba3433e7194f10'), ObjectId('67d93b1b80ba3433e7194f11'), ObjectId('67d93b1b80ba3433e7194f12'), ObjectId('67d93b1b80ba3433e7194f13'), ObjectId('67d93b1b80ba3433e7194f14'), ObjectId('67d93b1b80ba3433e7194f15'), ObjectId('67d93b1b80ba3433e7194f16'), ObjectId('67d93b1b80ba3433e7194f17'), ObjectId('67d93b1b80ba3433e7194f18'), ObjectId('67d93b1b80ba3433e7194f19'), ObjectId('67d93b1b80ba3433e7194f1a'), ObjectId('67d93b1b80ba3433e7194f1b'), ObjectId('67d93b1b80ba3433e7194f1c'), ObjectId('67d93b1b80ba3433e7194f1d'), ObjectId('67d93b1b80ba3433e7194f1e'), ObjectId('67d93b1b80ba3433e7194f1f'), ObjectId('67d93b1b80ba3433e7194f20'), ObjectId('67d93b1b80ba3433e7194f21'), ObjectId('67d93b1b80ba3433e7194f22'), ObjectId('67d93b1b80ba3433e7194f23'), ObjectId('67d93b1b80ba3433e7194f24'), ObjectId('67d93b1b80ba3433e7194f25'), ObjectId('67d93b1b80ba3433e7194f26'), ObjectId('67d93b1b80ba3433e7194f27'), ObjectId('67d93b1b80ba3433e7194f28'), ObjectId('67d93b1b80ba3433e7194f29'), ObjectId('67d93b1b80ba3433e7194f2a'), ObjectId('67d93b1b80ba3433e7194f2b'), ObjectId('67d93b1b80ba3433e7194f2c'), ObjectId('67d93b1b80ba3433e7194f2d'), ObjectId('67d93b1b80ba3433e7194f2e'), ObjectId('67d93b1b80ba3433e7194f2f'), ObjectId('67d93b1b80ba3433e7194f30'), ObjectId('67d93b1b80ba3433e7194f31'), ObjectId('67d93b1b80ba3433e7194f32'), ObjectId('67d93b1b80ba3433e7194f33'), ObjectId('67d93b1b80ba3433e7194f34'), ObjectId('67d93b1b80ba3433e7194f35'), ObjectId('67d93b1b80ba3433e7194f36'), ObjectId('67d93b1b80ba3433e7194f37'), ObjectId('67d93b1b80ba3433e7194f38'), ObjectId('67d93b1b80ba3433e7194f39'), ObjectId('67d93b1b80ba3433e7194f3a'), ObjectId('67d93b1b80ba3433e7194f3b'), ObjectId('67d93b1b80ba3433e7194f3c'), ObjectId('67d93b1b80ba3433e7194f3d'), ObjectId('67d93b1b80ba3433e7194f3e'), ObjectId('67d93b1b80ba3433e7194f3f'), ObjectId('67d93b1b80ba3433e7194f40'), ObjectId('67d93b1b80ba3433e7194f41'), ObjectId('67d93b1b80ba3433e7194f42'), ObjectId('67d93b1b80ba3433e7194f43'), ObjectId('67d93b1b80ba3433e7194f44'), ObjectId('67d93b1b80ba3433e7194f45'), ObjectId('67d93b1b80ba3433e7194f46'), ObjectId('67d93b1b80ba3433e7194f47'), ObjectId('67d93b1b80ba3433e7194f48'), ObjectId('67d93b1b80ba3433e7194f49'), ObjectId('67d93b1b80ba3433e7194f4a'), ObjectId('67d93b1b80ba3433e7194f4b'), ObjectId('67d93b1b80ba3433e7194f4c'), ObjectId('67d93b1b80ba3433e7194f4d'), ObjectId('67d93b1b80ba3433e7194f4e'), ObjectId('67d93b1b80ba3433e7194f4f'), ObjectId('67d93b1b80ba3433e7194f50'), ObjectId('67d93b1b80ba3433e7194f51'), ObjectId('67d93b1b80ba3433e7194f52'), ObjectId('67d93b1b80ba3433e7194f53'), ObjectId('67d93b1b80ba3433e7194f54'), ObjectId('67d93b1b80ba3433e7194f55'), ObjectId('67d93b1b80ba3433e7194f56'), ObjectId('67d93b1b80ba3433e7194f57'), ObjectId('67d93b1b80ba3433e7194f58'), ObjectId('67d93b1b80ba3433e7194f59'), ObjectId('67d93b1b80ba3433e7194f5a'), ObjectId('67d93b1b80ba3433e7194f5b'), ObjectId('67d93b1b80ba3433e7194f5c'), ObjectId('67d93b1b80ba3433e7194f5d'), ObjectId('67d93b1b80ba3433e7194f5e'), ObjectId('67d93b1b80ba3433e7194f5f'), ObjectId('67d93b1b80ba3433e7194f60'), ObjectId('67d93b1b80ba3433e7194f61'), ObjectId('67d93b1b80ba3433e7194f62'), ObjectId('67d93b1b80ba3433e7194f63'), ObjectId('67d93b1b80ba3433e7194f64'), ObjectId('67d93b1b80ba3433e7194f65'), ObjectId('67d93b1b80ba3433e7194f66'), ObjectId('67d93b1b80ba3433e7194f67'), ObjectId('67d93b1b80ba3433e7194f68'), ObjectId('67d93b1b80ba3433e7194f69'), ObjectId('67d93b1b80ba3433e7194f6a'), ObjectId('67d93b1b80ba3433e7194f6b'), ObjectId('67d93b1b80ba3433e7194f6c'), ObjectId('67d93b1b80ba3433e7194f6d'), ObjectId('67d93b1b80ba3433e7194f6e'), ObjectId('67d93b1b80ba3433e7194f6f'), ObjectId('67d93b1b80ba3433e7194f70'), ObjectId('67d93b1b80ba3433e7194f71'), ObjectId('67d93b1b80ba3433e7194f72'), ObjectId('67d93b1b80ba3433e7194f73'), ObjectId('67d93b1b80ba3433e7194f74'), ObjectId('67d93b1b80ba3433e7194f75'), ObjectId('67d93b1b80ba3433e7194f76'), ObjectId('67d93b1b80ba3433e7194f77'), ObjectId('67d93b1b80ba3433e7194f78'), ObjectId('67d93b1b80ba3433e7194f79'), ObjectId('67d93b1b80ba3433e7194f7a'), ObjectId('67d93b1b80ba3433e7194f7b'), ObjectId('67d93b1b80ba3433e7194f7c'), ObjectId('67d93b1b80ba3433e7194f7d'), ObjectId('67d93b1b80ba3433e7194f7e'), ObjectId('67d93b1b80ba3433e7194f7f'), ObjectId('67d93b1b80ba3433e7194f80'), ObjectId('67d93b1b80ba3433e7194f81'), ObjectId('67d93b1b80ba3433e7194f82'), ObjectId('67d93b1b80ba3433e7194f83'), ObjectId('67d93b1b80ba3433e7194f84'), ObjectId('67d93b1b80ba3433e7194f85'), ObjectId('67d93b1b80ba3433e7194f86'), ObjectId('67d93b1b80ba3433e7194f87'), ObjectId('67d93b1b80ba3433e7194f88'), ObjectId('67d93b1b80ba3433e7194f89'), ObjectId('67d93b1b80ba3433e7194f8a'), ObjectId('67d93b1b80ba3433e7194f8b'), ObjectId('67d93b1b80ba3433e7194f8c'), ObjectId('67d93b1b80ba3433e7194f8d'), ObjectId('67d93b1b80ba3433e7194f8e'), ObjectId('67d93b1b80ba3433e7194f8f'), ObjectId('67d93b1b80ba3433e7194f90'), ObjectId('67d93b1b80ba3433e7194f91'), ObjectId('67d93b1b80ba3433e7194f92'), ObjectId('67d93b1b80ba3433e7194f93'), ObjectId('67d93b1b80ba3433e7194f94'), ObjectId('67d93b1b80ba3433e7194f95'), ObjectId('67d93b1b80ba3433e7194f96'), ObjectId('67d93b1b80ba3433e7194f97'), ObjectId('67d93b1b80ba3433e7194f98'), ObjectId('67d93b1b80ba3433e7194f99'), ObjectId('67d93b1b80ba3433e7194f9a'), ObjectId('67d93b1b80ba3433e7194f9b'), ObjectId('67d93b1b80ba3433e7194f9c'), ObjectId('67d93b1b80ba3433e7194f9d'), ObjectId('67d93b1b80ba3433e7194f9e'), ObjectId('67d93b1b80ba3433e7194f9f'), ObjectId('67d93b1b80ba3433e7194fa0'), ObjectId('67d93b1b80ba3433e7194fa1'), ObjectId('67d93b1b80ba3433e7194fa2'), ObjectId('67d93b1b80ba3433e7194fa3'), ObjectId('67d93b1b80ba3433e7194fa4'), ObjectId('67d93b1b80ba3433e7194fa5'), ObjectId('67d93b1b80ba3433e7194fa6'), ObjectId('67d93b1b80ba3433e7194fa7'), ObjectId('67d93b1b80ba3433e7194fa8'), ObjectId('67d93b1b80ba3433e7194fa9'), ObjectId('67d93b1b80ba3433e7194faa'), ObjectId('67d93b1b80ba3433e7194fab'), ObjectId('67d93b1b80ba3433e7194fac'), ObjectId('67d93b1b80ba3433e7194fad'), ObjectId('67d93b1b80ba3433e7194fae'), ObjectId('67d93b1b80ba3433e7194faf'), ObjectId('67d93b1b80ba3433e7194fb0'), ObjectId('67d93b1b80ba3433e7194fb1'), ObjectId('67d93b1b80ba3433e7194fb2'), ObjectId('67d93b1b80ba3433e7194fb3'), ObjectId('67d93b1b80ba3433e7194fb4'), ObjectId('67d93b1b80ba3433e7194fb5'), ObjectId('67d93b1b80ba3433e7194fb6'), ObjectId('67d93b1b80ba3433e7194fb7'), ObjectId('67d93b1b80ba3433e7194fb8'), ObjectId('67d93b1b80ba3433e7194fb9'), ObjectId('67d93b1b80ba3433e7194fba'), ObjectId('67d93b1b80ba3433e7194fbb'), ObjectId('67d93b1b80ba3433e7194fbc'), ObjectId('67d93b1b80ba3433e7194fbd'), ObjectId('67d93b1b80ba3433e7194fbe'), ObjectId('67d93b1b80ba3433e7194fbf'), ObjectId('67d93b1b80ba3433e7194fc0'), ObjectId('67d93b1b80ba3433e7194fc1'), ObjectId('67d93b1b80ba3433e7194fc2'), ObjectId('67d93b1b80ba3433e7194fc3'), ObjectId('67d93b1b80ba3433e7194fc4'), ObjectId('67d93b1b80ba3433e7194fc5'), ObjectId('67d93b1b80ba3433e7194fc6'), ObjectId('67d93b1b80ba3433e7194fc7'), ObjectId('67d93b1b80ba3433e7194fc8'), ObjectId('67d93b1b80ba3433e7194fc9'), ObjectId('67d93b1b80ba3433e7194fca'), ObjectId('67d93b1b80ba3433e7194fcb'), ObjectId('67d93b1b80ba3433e7194fcc'), ObjectId('67d93b1b80ba3433e7194fcd'), ObjectId('67d93b1b80ba3433e7194fce'), ObjectId('67d93b1b80ba3433e7194fcf'), ObjectId('67d93b1b80ba3433e7194fd0'), ObjectId('67d93b1b80ba3433e7194fd1'), ObjectId('67d93b1b80ba3433e7194fd2'), ObjectId('67d93b1b80ba3433e7194fd3'), ObjectId('67d93b1b80ba3433e7194fd4'), ObjectId('67d93b1b80ba3433e7194fd5'), ObjectId('67d93b1b80ba3433e7194fd6'), ObjectId('67d93b1b80ba3433e7194fd7'), ObjectId('67d93b1b80ba3433e7194fd8'), ObjectId('67d93b1b80ba3433e7194fd9'), ObjectId('67d93b1b80ba3433e7194fda'), ObjectId('67d93b1b80ba3433e7194fdb'), ObjectId('67d93b1b80ba3433e7194fdc'), ObjectId('67d93b1b80ba3433e7194fdd'), ObjectId('67d93b1b80ba3433e7194fde'), ObjectId('67d93b1b80ba3433e7194fdf'), ObjectId('67d93b1b80ba3433e7194fe0'), ObjectId('67d93b1b80ba3433e7194fe1'), ObjectId('67d93b1b80ba3433e7194fe2'), ObjectId('67d93b1b80ba3433e7194fe3'), ObjectId('67d93b1b80ba3433e7194fe4'), ObjectId('67d93b1b80ba3433e7194fe5'), ObjectId('67d93b1b80ba3433e7194fe6'), ObjectId('67d93b1b80ba3433e7194fe7'), ObjectId('67d93b1b80ba3433e7194fe8'), ObjectId('67d93b1b80ba3433e7194fe9'), ObjectId('67d93b1b80ba3433e7194fea'), ObjectId('67d93b1b80ba3433e7194feb'), ObjectId('67d93b1b80ba3433e7194fec'), ObjectId('67d93b1b80ba3433e7194fed'), ObjectId('67d93b1b80ba3433e7194fee'), ObjectId('67d93b1b80ba3433e7194fef'), ObjectId('67d93b1b80ba3433e7194ff0'), ObjectId('67d93b1b80ba3433e7194ff1'), ObjectId('67d93b1b80ba3433e7194ff2'), ObjectId('67d93b1b80ba3433e7194ff3'), ObjectId('67d93b1b80ba3433e7194ff4'), ObjectId('67d93b1b80ba3433e7194ff5'), ObjectId('67d93b1b80ba3433e7194ff6'), ObjectId('67d93b1b80ba3433e7194ff7'), ObjectId('67d93b1b80ba3433e7194ff8'), ObjectId('67d93b1b80ba3433e7194ff9'), ObjectId('67d93b1b80ba3433e7194ffa'), ObjectId('67d93b1b80ba3433e7194ffb'), ObjectId('67d93b1b80ba3433e7194ffc'), ObjectId('67d93b1b80ba3433e7194ffd'), ObjectId('67d93b1b80ba3433e7194ffe'), ObjectId('67d93b1b80ba3433e7194fff'), ObjectId('67d93b1b80ba3433e7195000'), ObjectId('67d93b1b80ba3433e7195001'), ObjectId('67d93b1b80ba3433e7195002'), ObjectId('67d93b1b80ba3433e7195003'), ObjectId('67d93b1b80ba3433e7195004'), ObjectId('67d93b1b80ba3433e7195005'), ObjectId('67d93b1b80ba3433e7195006'), ObjectId('67d93b1b80ba3433e7195007'), ObjectId('67d93b1b80ba3433e7195008'), ObjectId('67d93b1b80ba3433e7195009'), ObjectId('67d93b1b80ba3433e719500a'), ObjectId('67d93b1b80ba3433e719500b'), ObjectId('67d93b1b80ba3433e719500c'), ObjectId('67d93b1b80ba3433e719500d'), ObjectId('67d93b1b80ba3433e719500e'), ObjectId('67d93b1b80ba3433e719500f'), ObjectId('67d93b1b80ba3433e7195010'), ObjectId('67d93b1b80ba3433e7195011'), ObjectId('67d93b1b80ba3433e7195012'), ObjectId('67d93b1b80ba3433e7195013'), ObjectId('67d93b1b80ba3433e7195014'), ObjectId('67d93b1b80ba3433e7195015'), ObjectId('67d93b1b80ba3433e7195016'), ObjectId('67d93b1b80ba3433e7195017'), ObjectId('67d93b1b80ba3433e7195018'), ObjectId('67d93b1b80ba3433e7195019'), ObjectId('67d93b1b80ba3433e719501a'), ObjectId('67d93b1b80ba3433e719501b'), ObjectId('67d93b1b80ba3433e719501c'), ObjectId('67d93b1b80ba3433e719501d'), ObjectId('67d93b1b80ba3433e719501e'), ObjectId('67d93b1b80ba3433e719501f'), ObjectId('67d93b1b80ba3433e7195020'), ObjectId('67d93b1b80ba3433e7195021'), ObjectId('67d93b1b80ba3433e7195022'), ObjectId('67d93b1b80ba3433e7195023'), ObjectId('67d93b1b80ba3433e7195024'), ObjectId('67d93b1b80ba3433e7195025'), ObjectId('67d93b1b80ba3433e7195026'), ObjectId('67d93b1b80ba3433e7195027'), ObjectId('67d93b1b80ba3433e7195028'), ObjectId('67d93b1b80ba3433e7195029'), ObjectId('67d93b1b80ba3433e719502a'), ObjectId('67d93b1b80ba3433e719502b'), ObjectId('67d93b1b80ba3433e719502c'), ObjectId('67d93b1b80ba3433e719502d'), ObjectId('67d93b1b80ba3433e719502e'), ObjectId('67d93b1b80ba3433e719502f'), ObjectId('67d93b1b80ba3433e7195030'), ObjectId('67d93b1b80ba3433e7195031'), ObjectId('67d93b1b80ba3433e7195032'), ObjectId('67d93b1b80ba3433e7195033'), ObjectId('67d93b1b80ba3433e7195034'), ObjectId('67d93b1b80ba3433e7195035'), ObjectId('67d93b1b80ba3433e7195036'), ObjectId('67d93b1b80ba3433e7195037'), ObjectId('67d93b1b80ba3433e7195038'), ObjectId('67d93b1b80ba3433e7195039'), ObjectId('67d93b1b80ba3433e719503a'), ObjectId('67d93b1b80ba3433e719503b'), ObjectId('67d93b1b80ba3433e719503c'), ObjectId('67d93b1b80ba3433e719503d'), ObjectId('67d93b1b80ba3433e719503e'), ObjectId('67d93b1b80ba3433e719503f'), ObjectId('67d93b1b80ba3433e7195040'), ObjectId('67d93b1b80ba3433e7195041'), ObjectId('67d93b1b80ba3433e7195042'), ObjectId('67d93b1b80ba3433e7195043'), ObjectId('67d93b1b80ba3433e7195044'), ObjectId('67d93b1b80ba3433e7195045'), ObjectId('67d93b1b80ba3433e7195046'), ObjectId('67d93b1b80ba3433e7195047'), ObjectId('67d93b1b80ba3433e7195048'), ObjectId('67d93b1b80ba3433e7195049'), ObjectId('67d93b1b80ba3433e719504a'), ObjectId('67d93b1b80ba3433e719504b'), ObjectId('67d93b1b80ba3433e719504c'), ObjectId('67d93b1b80ba3433e719504d'), ObjectId('67d93b1b80ba3433e719504e'), ObjectId('67d93b1b80ba3433e719504f'), ObjectId('67d93b1b80ba3433e7195050'), ObjectId('67d93b1b80ba3433e7195051'), ObjectId('67d93b1b80ba3433e7195052'), ObjectId('67d93b1b80ba3433e7195053'), ObjectId('67d93b1b80ba3433e7195054'), ObjectId('67d93b1b80ba3433e7195055'), ObjectId('67d93b1b80ba3433e7195056'), ObjectId('67d93b1b80ba3433e7195057'), ObjectId('67d93b1b80ba3433e7195058'), ObjectId('67d93b1b80ba3433e7195059'), ObjectId('67d93b1b80ba3433e719505a'), ObjectId('67d93b1b80ba3433e719505b'), ObjectId('67d93b1b80ba3433e719505c'), ObjectId('67d93b1b80ba3433e719505d'), ObjectId('67d93b1b80ba3433e719505e'), ObjectId('67d93b1b80ba3433e719505f'), ObjectId('67d93b1b80ba3433e7195060'), ObjectId('67d93b1b80ba3433e7195061'), ObjectId('67d93b1b80ba3433e7195062'), ObjectId('67d93b1b80ba3433e7195063'), ObjectId('67d93b1b80ba3433e7195064'), ObjectId('67d93b1b80ba3433e7195065'), ObjectId('67d93b1b80ba3433e7195066'), ObjectId('67d93b1b80ba3433e7195067'), ObjectId('67d93b1b80ba3433e7195068'), ObjectId('67d93b1b80ba3433e7195069'), ObjectId('67d93b1b80ba3433e719506a'), ObjectId('67d93b1b80ba3433e719506b'), ObjectId('67d93b1b80ba3433e719506c'), ObjectId('67d93b1b80ba3433e719506d'), ObjectId('67d93b1b80ba3433e719506e'), ObjectId('67d93b1b80ba3433e719506f'), ObjectId('67d93b1b80ba3433e7195070'), ObjectId('67d93b1b80ba3433e7195071'), ObjectId('67d93b1b80ba3433e7195072'), ObjectId('67d93b1b80ba3433e7195073'), ObjectId('67d93b1b80ba3433e7195074'), ObjectId('67d93b1b80ba3433e7195075'), ObjectId('67d93b1b80ba3433e7195076'), ObjectId('67d93b1b80ba3433e7195077'), ObjectId('67d93b1b80ba3433e7195078'), ObjectId('67d93b1b80ba3433e7195079'), ObjectId('67d93b1b80ba3433e719507a'), ObjectId('67d93b1b80ba3433e719507b'), ObjectId('67d93b1b80ba3433e71950

In [24]:
'''
{
  "mappings": {
    "dynamic": true,
    "fields": {
      "embedding": {
        "type": "knnVector",
        "dimensions": 1024,
        "similarity": "cosine"
      }
    }
  }
}
'''

'\n{\n  "mappings": {\n    "dynamic": true,\n    "fields": {\n      "embedding": {\n        "type": "knnVector",\n        "dimensions": 1024,\n        "similarity": "cosine"\n      }\n    }\n  }\n}\n'

In [25]:
def get_embedding(text:str)->list[float]:

  if not text.strip():
    print("attempted to get embedding for empty text.")
    return []

  embedding=embedding_model.encode(text)
  return embedding.tolist()

In [26]:
def vector_search(user_query,collection):

  query_embedding=get_embedding(user_query)
  print(query_embedding)

  if query_embedding is None:
    return "Invalid query or embeddig is failed"

  pipeline=[

            {
                "$vectorSearch":{

                "index": "vector_index",
                "queryVector": query_embedding,
                "path": "embedding",
                "numCandidates": 150,  # Number of candidate matches to consider
                "limit": 4,  # Return top 4 matches


                }

            },

              {
                 "$project":{

                "fullplot": 1,  # Include the plot field
                "title": 1,  # Include the title field
                "genres": 1,  # Include the genres field
                "score": {"$meta": "vectorSearchScore"},  # Include the search score
                 }

            }

           ]

  result=collection.aggregate(pipeline)
  return list(result)

In [27]:
query=vector_search("what is the best horror movie to watch and why?",collection)

[0.019185910001397133, -0.015472973696887493, -0.039554622024297714, 0.0023692885879427195, -0.0026592393405735493, 0.005181845277547836, -0.007513183634728193, 0.04510664567351341, -0.01811216212809086, 0.04297339543700218, 0.013434004038572311, -0.002870751777663827, 0.005479604005813599, -0.031249219551682472, -0.004083319567143917, -0.031060349196195602, -0.041057247668504715, -0.030109725892543793, -0.032163724303245544, 0.0274803563952446, -0.003167578484863043, 0.016843503341078758, -0.04414500296115875, -0.023998111486434937, -0.01558186486363411, 0.017874477431178093, 0.021615177392959595, -0.03042469173669815, 0.04588275030255318, 0.07223064452409744, 0.0023236412089318037, -0.04596633091568947, 0.026177143678069115, -0.048973847180604935, -0.03348347917199135, -0.010094979777932167, 0.05488929525017738, 0.0015838578110560775, -0.0027255306486040354, -0.03803258389234543, 0.016657168045639992, 0.014302327297627926, 0.04556028172373772, -0.011216199956834316, -0.05046370252966881, 0.0023860917426645756, 0.017925577238202095, -0.03008187562227249, -0.007713125087320805, -0.021677715703845024, 0.0025280488189309835, -0.03760182112455368, 0.01106012798845768, 0.006693193688988686, 0.013570702634751797, 0.026865992695093155, -0.011295432224869728, -0.013143101707100868, 0.00019351211085449904, 0.044105056673288345, 0.021538350731134415, -0.021799027919769287, 0.024568943306803703, -0.028306448832154274, 0.015344311483204365, 0.024441946297883987, 0.01056041568517685, -0.030671684071421623, 0.028781568631529808, 0.03318262845277786, 0.019338801503181458, -0.0029937508516013622, -0.019163792952895164, 0.019363807514309883, 0.011445790529251099, 0.020723124966025352, -0.01135885901749134, 0.02779216133058071, -0.015587632544338703, -0.020335908979177475, 0.010521955788135529, 0.05448822304606438, 0.02120736986398697, 0.015374409966170788, -0.07038009911775589, -0.045299988240003586, -0.017124833539128304, 0.02929661050438881, -0.014126746915280819, 0.038227859884500504, 0.035666659474372864, 0.0272141732275486, 0.011118212714791298, -0.03238028660416603, 0.04557008668780327, 0.05568911135196686, -0.03874794766306877, -0.005883847828954458, 0.00319117633625865, -0.017282338812947273, 0.005285186227411032, 0.044459495693445206, -0.004427382722496986, 0.02838730625808239, -0.03157701715826988, -0.005482762586325407, 0.025338752195239067, -0.004885309375822544, -0.024914659559726715, -0.05109066516160965, -0.0074899629689753056, -0.03672900050878525, 0.009195303544402122, 0.010751563124358654, -0.011365892365574837, 0.03295494243502617, -0.004312325268983841, 0.04387519881129265, -0.059020403772592545, 0.023117467761039734, 0.01511061005294323, -0.00029511970933526754, 0.054292403161525726, -0.03185069561004639, 0.05932874232530594, -0.04194684699177742, -0.007042140234261751, 0.03700249642133713, -0.03655995801091194, -0.0068397740833461285, -0.0023263576440513134, -0.029350562021136284, 0.003167265560477972, 0.042417049407958984, 0.017486626282334328, 0.01542280986905098, -0.0034260910470038652, -0.007652462925761938, 0.024394566193223, -0.0518614687025547, 0.042092952877283096, 0.00630158931016922, 0.008150366134941578, 0.07824898511171341, 0.007197114638984203, -0.008467062376439571, 0.018384138122200966, -0.008630874566733837, -0.008001141250133514, 0.03481712564826012, -0.006094435695558786, 0.0023830689024180174, 0.005015678238123655, 0.018067052587866783, -0.013551920652389526, -0.023615283891558647, -0.021410617977380753, 0.02023153565824032, 0.008841213770210743, 0.06210239231586456, 0.040512263774871826, 0.022513320669531822, -0.034654125571250916, 0.03884599730372429, -0.0021718479692935944, 0.04867856949567795, -0.03257758170366287, 0.000907470122911036, -0.009817066602408886, -0.021265942603349686, 0.012817616574466228, 0.004213869106024504, 0.008234712295234203, 0.0016958533087745309, 0.030094845220446587, 0.04801258072257042, 0.048210397362709045, -0.0357104130089283, 0.024411803111433983, 0.04366960749030113, -0.028004726395010948, -0.00888108927756548, -0.01462821289896965, 0.08361644297838211, -0.014546808786690235, -0.023770879954099655, 0.007310719229280949, -0.03333676606416702, -0.05331197381019592, -0.020663587376475334, -0.04155842959880829, 0.01944727823138237, -0.01920161210000515, 0.021387439221143723, 0.022920500487089157, 0.01137643400579691, -0.029181530699133873, -0.01678439788520336, -0.0024862675927579403, -0.047684866935014725, -0.007824884727597237, 0.07042437791824341, -0.0365186482667923, 0.0218748040497303, 0.011032783426344395, -0.03732703998684883, 0.04041549935936928, 0.061254825443029404, -0.023774560540914536, -0.024698421359062195, 0.033281270414590836, 0.008721924386918545, 0.013296365737915039, 0.010940201580524445, -0.028574122115969658, 0.011603787541389465, -0.01649029366672039, 0.04901757463812828, -0.03695850819349289, 0.0356656014919281, -0.020912451669573784, 0.010374203324317932, 0.018073922023177147, 0.04076733440160751, 0.010249401442706585, -0.006932950112968683, 0.01317831315100193, 0.03050076775252819, -0.02378183975815773, 0.022923991084098816, 0.015516052953898907, 0.049822453409433365, 0.03889412432909012, 0.041692838072776794, 0.027394194155931473, 0.007180498447269201, 0.04679451137781143, 0.0218400489538908, -0.011140141636133194, 0.035642143338918686, -0.0214207973331213, -0.0047433217987418175, 0.03576232120394707, 0.04442803934216499, -0.024436920881271362, 0.026087576523423195, -0.028007712215185165, -0.02513802982866764, -0.03626834601163864, 0.022240446880459785, 0.02108944021165371, 0.025470662862062454, 0.03871038928627968, 0.010867365635931492, -0.01682247221469879, 0.02106027491390705, 0.03350116312503815, 0.06531915813684464, -0.0056921374052762985, -0.005985702387988567, -0.030677344650030136, 0.015677182003855705, 0.0317133329808712, 0.020100638270378113, 0.053008243441581726, 0.007643850054591894, -0.005791191477328539, 0.012355659157037735, -0.05579022318124771, -0.07652191817760468, -0.03582775592803955, -0.042259812355041504, -0.012948264367878437, -0.04300167039036751, -0.038529857993125916, -0.0025276527740061283, 0.0299006886780262, -0.022248446941375732, -0.0017009045695886016, -0.015184889547526836, -0.025915782898664474, 0.006076591555029154, -0.013868960551917553, 0.026459677144885063, -0.01826384849846363, 0.03126632794737816, -0.03586892783641815, 0.037166573107242584, -0.03319910913705826, 0.04537452757358551, -0.02138287015259266, -0.0044157844968140125, 0.006134622730314732, 0.01958155445754528, 0.04254359006881714, 0.005905126221477985, -0.02916431427001953, -0.022568166255950928, -0.022875279188156128, -0.06647872179746628, 0.022639133036136627, -0.011339185759425163, -0.01471618190407753, 0.012011047452688217, -0.017216043546795845, 0.043484192341566086, 0.034886859357357025, -0.01645173877477646, 0.031356457620859146, 0.023803850635886192, -0.05105475336313248, 0.025596458464860916, -0.005357284098863602, 0.01876199059188366, -0.04783881828188896, 0.06260153651237488, 0.021144123747944832, -2.0018658688059077e-05, -0.0053124637342989445, 0.020834295079112053, -0.0174869317561388, 0.00185605906881392, 0.009527288377285004, -0.019396325573325157, -0.025708544999361038, 0.05055324360728264, 0.0071607851423323154, -0.043045513331890106, 0.01837698370218277, -0.008618224412202835, 0.000331906252540648, -0.018265709280967712, -0.03617514297366142, 0.051165346056222916, 0.038280416280031204, 0.054261818528175354, -0.03646085038781166, -0.03900839388370514, -0.028841791674494743, 0.034725818783044815, 0.04036795720458031, -0.017953338101506233, 0.009746544063091278, 0.04721887782216072, 0.012025421485304832, 0.025486793369054794, 0.0011298081371933222, -0.008161772042512894, 0.019771410152316093, 0.007591726258397102, -0.003687311662361026, -0.004959978628903627, 0.011812776327133179, -0.015729518607258797, 0.027522725984454155, 0.0385948121547699, -0.04243312403559685, 0.046922385692596436, 0.003851915244013071, 0.012147312052547932, 0.029792312532663345, 0.013567695394158363, -0.008446128107607365, -0.01081452053040266, -0.04356777295470238, -0.06818487495183945, 0.03195538371801376, -0.015776922926306725, 0.05179142206907272, -0.058163512498140335, 0.06111207231879234, 0.011737563647329807, -0.0355338491499424, 0.0391046479344368, -0.024787330999970436, 0.02408098243176937, -0.007841049693524837, -0.017160629853606224, 0.014096180908381939, -0.025531891733407974, 0.005327573511749506, -0.017433131113648415, 0.06304161995649338, 0.0754329264163971, 0.015719491988420486, 0.05401410534977913, -0.027241243049502373, -0.05042767897248268, -0.025497449561953545, 0.0015442597214132547, 0.0042600370943546295, -0.035203684121370316, 0.05002289265394211, -0.02322753332555294, -0.08523961156606674, -0.046548984944820404, 0.029208999127149582, 0.034542206674814224, 0.02241302654147148, -0.029873503372073174, 0.0001572485052747652, -0.005502296611666679, -0.014290614984929562, 0.0342947319149971, -0.0019598521757870913, 0.03817213326692581, -0.01646989770233631, 0.045612066984176636, -0.006666866596788168, -0.0154105294495821, -0.01791655458509922, -0.012537558563053608, -0.05363593250513077, 0.045358799397945404, -0.0029234651010483503, -0.0090419827029109, -0.012383087538182735, 0.011324094608426094, 0.03547544777393341, 0.021812768653035164, -0.019498124718666077, 0.011525479145348072, -0.012560003437101841, 0.028600940480828285, 0.005268752574920654, -0.07287373393774033, -0.014644181355834007, -0.0354132317006588, 0.05065644904971123, 0.04908338561654091, 0.011445094831287861, -0.035250045359134674, 0.004302729852497578, -0.031497396528720856, -0.0645153746008873, 0.010592930018901825, 0.0507841594517231, -0.025625484064221382, 0.03679648041725159, -0.05012013390660286, 0.01597481220960617, 0.002764454111456871, 0.0015346708241850138, -0.007717054802924395, -0.01256837509572506, 0.028139807283878326, 0.032376449555158615, 0.024113383144140244, -0.0008315290906466544, -0.016307169571518898, -0.011562543921172619, -0.07263292372226715, 0.0011903253616765141, 0.022668443620204926, -0.03263673186302185, 0.03516514226794243, 0.030683103948831558, 0.01946830563247204, 0.04351859167218208, -0.017278099432587624, 0.07233159989118576, -0.055127158761024475, 0.03622117638587952, -0.023955490440130234, -0.04078449308872223, 0.05109396204352379, 0.02609163522720337, -0.022817716002464294, 0.05051669105887413, 0.001186067471280694, 0.001968285534530878, -0.009243459440767765, 0.04923594743013382, -0.04701746627688408, 0.04077018052339554, -0.04076743125915527, 0.005193388555198908, 0.01619444414973259, -0.0350891537964344, 0.015681879594922066, -0.03688391298055649, 0.026260778307914734, 0.014252329245209694, 0.022447621449828148, -0.04101818427443504, -0.03403439745306969, -0.02325611375272274, -0.03709131479263306, 0.003350503509864211, -0.005805646069347858, 0.020454660058021545, 0.015604483895003796, -0.022060293704271317, -0.020030690357089043, -0.018010597676038742, 0.0007797737489454448, 0.007693887688219547, 0.02321472018957138, -0.01318161841481924, 0.029439950361847878, -0.009283572435379028, -0.017016394063830376, -0.021441495046019554, -0.004634223412722349, 0.015105937607586384, -0.02790021151304245, -0.04936208203434944, 0.004174379166215658, -0.035690926015377045, -0.007284415885806084, -0.03441614657640457, 0.017120476812124252, -0.05422944575548172, 0.06041428819298744, 0.0069463555701076984, 0.041155800223350525, -0.0033390831667929888, -0.006697528064250946, -0.02491442859172821, 0.04574885219335556, 0.010451899841427803, -0.029245244339108467, -0.025553936138749123, 0.03483682498335838, -0.02119254320859909, 0.03171221539378166, -0.010004783980548382, -0.016670266166329384, -0.09865669161081314, -0.030303411185741425, 0.01166821550577879, -0.03820310905575752, 0.0028980181086808443, -0.034960366785526276, -0.032910097390413284, -0.020274195820093155, 0.017710456624627113, 0.0025958383921533823, 0.004258865024894476, -0.0043897926807403564, -0.011577270925045013, -0.028743186965584755, -0.0007525733672082424, -0.03422616422176361, -0.028095221146941185, 0.005800540093332529, -0.005880641285330057, 0.06386715173721313, -0.0062408712692558765, 0.04142496734857559, 0.0019615895580500364, 0.03096199594438076, 0.02495087869465351, -0.010406764224171638, -0.05980538949370384, -0.010577917098999023, 0.009262594394385815, -0.004312909673899412, -0.023150525987148285, 0.023656511679291725, -0.054919227957725525, 0.011977676302194595, -0.043747466057538986, 0.010738412849605083, -0.00822752807289362, -0.024477209895849228, 0.0020585921593010426, 0.008173693902790546, 0.06306767463684082, -0.03221919387578964, -0.02305232174694538, 0.0024109031073749065, 0.04274037480354309, 0.0897863432765007, 0.0028557043988257647, -0.03453761711716652, -0.030182475224137306, -0.013518253341317177, -0.04712071269750595, 0.040778856724500656, -0.06109818443655968, -0.023814644664525986, -0.05072547867894173, 0.004147761035710573, 0.05331016704440117, -0.005132082384079695, 0.02387208677828312, 0.05782981961965561, -0.008879801258444786, -0.006859880406409502, -0.013202769681811333, 0.008315227925777435, 0.05271323025226593, -0.05233211815357208, 0.00996811781078577, 0.000613131036516279, -0.036987222731113434, -0.004852964077144861, -0.05060684308409691, -0.059832312166690826, -0.0602233000099659, 0.030840998515486717, 0.08705289661884308, -0.04687226191163063, 0.03702192008495331, -0.011082921177148819, -0.060925669968128204, -0.04660087451338768, 0.038146261125802994, -0.002224331023171544, 0.015713991597294807, 0.032998375594615936, -0.001486599212512374, -0.050842270255088806, -0.03847356513142586, 0.0290440171957016, 0.009926699101924896, -0.02380121871829033, 0.04800761863589287, -0.001409512129612267, -0.041179388761520386, 0.042356885969638824, 0.024763599038124084, -0.059517476707696915, -0.04960506409406662, -0.01772334612905979, 0.01104963943362236, 0.022265397012233734, -0.0371258519589901, 0.0007927722181193531, -0.03450663760304451, 0.013134272769093513, 0.009239311330020428, 0.03983594477176666, -0.02811402827501297, 0.029821746051311493, 0.04696597531437874, 0.0107656829059124, -0.05601649731397629, 0.015335951000452042, -0.025011658668518066, 0.022551989182829857, -0.0518459677696228, -0.03197072818875313, -0.03387908637523651, 0.0016888335812836885, -0.012036152184009552, 0.030316665768623352, -0.010381768457591534, 0.005567510146647692, 0.020053792744874954, -0.011086573824286461, 0.07029968500137329, 0.013899133540689945, -0.017137344926595688, -0.0017857629572972655, -0.020327091217041016, -0.05856867507100105, -0.03785786032676697, 0.0037797007244080305, 0.019799133762717247, 0.010910398326814175, -0.0582394041121006, 0.008289818651974201, 0.018351247534155846, -0.017175991088151932, 0.0035973438061773777, -0.04992559179663658, -0.014108064584434032, -0.052579332143068314, -0.022051796317100525, -0.0036977711133658886, -0.0008083553984761238, -0.021884404122829437, 0.027355628088116646, 0.0016089084092527628, -0.029270870611071587, 0.008037271909415722, -0.01233935821801424, 0.006758151575922966, 0.005729355849325657, -0.05791003257036209, 0.039133597165346146, -0.01663668267428875, -0.04358699172735214, -0.029415691271424294, 0.0259841401129961, 0.015434668399393559, 0.0012913133250549436, -0.031619854271411896, 0.008552019484341145, -0.012817532755434513, 0.017244989052414894, -0.01794673316180706, 0.0075566465966403484, -0.017268892377614975, -0.013014272786676884, -0.0025602441746741533, 0.03092239610850811, -0.00822498369961977, 0.05268019065260887, 0.003982044756412506, -0.010345801711082458, 0.033131103962659836, -0.0007086043478921056, -0.05318320542573929, 0.009540838189423084, 0.0024098705034703016, -0.02192225493490696, 0.0348907932639122, -0.027894610539078712, -0.030460776761174202, -0.043980225920677185, -0.04979213699698448, 0.02800043299794197, 0.015616591088473797, 0.008705447427928448, -0.030512038618326187, 0.023569243028759956, 0.009336842224001884, 0.04857621714472771, -0.015953876078128815, 0.026485437527298927, 0.01798623614013195, 0.006866412702947855, 0.009853478521108627, -0.025783926248550415, 0.028726400807499886, 0.03419649600982666, 0.020164860412478447, -0.04628116264939308, 0.0016593493055552244, -0.03997602313756943, 0.020715540274977684, 0.037623390555381775, -0.02516072429716587, -0.026231801137328148, -0.05005909129977226, -0.03582175448536873, -0.0035403778310865164, 0.049556244164705276, 0.009503222070634365, -0.021995751187205315, 0.02197861112654209, -0.046443864703178406, -0.04055074602365494, 0.008513601496815681, -0.06697090715169907, 0.02134852670133114, 0.01528346911072731, 0.008236505091190338, -0.006347618997097015, -0.05902014672756195, -0.047221921384334564, 0.0062292213551700115, -0.01935827173292637, 0.013838448561728, -0.0035467285197228193, 0.03502143919467926, -0.0330880768597126, 0.08082041144371033, -0.017953578382730484, -0.0033512345980852842, -0.0018916939152404666, 0.08003555983304977, -0.043224405497312546, 0.011126039549708366, -0.0014269908424466848, -0.0036792433820664883, 0.01076787430793047, -0.015071810223162174, 0.014763918705284595, 0.012500982731580734, 0.014686591923236847, 0.022492872551083565, -0.024197550490498543, 0.01778542622923851, -0.02145886979997158, 0.017565404996275902, 0.031441278755664825, -0.023254210129380226, -0.02611822634935379, 0.021155891939997673, 0.009579522535204887, 0.001304343924857676, -0.07001359015703201, 0.033840734511613846, 0.03987875208258629, -0.00765923922881484, 0.05010703206062317, 0.02813655696809292, 0.06265094876289368, -0.01616695150732994, 0.01435082033276558, 0.00952649861574173, 0.04662130028009415, -0.010925988666713238, 0.021460486575961113, 0.015947043895721436, 0.012952882796525955, 0.03177023306488991, 0.001319791073910892, -0.011859897524118423, 0.042298439890146255, 0.03402966633439064, -0.02565493993461132, -0.002025627763941884, 0.010610254481434822, 0.01609676517546177, -0.008174492977559566, 0.014449573121964931, -0.006015544291585684, 0.003943317569792271, 0.006568341515958309, -0.0038125759456306696, 0.019119830802083015, 0.06984274089336395, -0.018593503162264824, -0.008790143765509129, -0.00018093077233061194, -0.02554413303732872, 0.03247364982962608, 0.058784112334251404, -0.00012884648458566517, 0.009333941154181957, 0.012937513180077076, 0.01868465356528759, -0.037260740995407104, 0.03305860236287117, 0.05203339457511902, -0.0010003546485677361, -0.027955709025263786, 0.0031926599331200123, 0.024860206991434097, -0.029471591114997864, -0.042722687125205994, -0.012206854298710823, -0.03535056486725807, 0.030837366357445717, -0.01065858080983162, -0.002102593192830682, 0.06250819563865662, -0.05243203788995743, -0.013654349371790886, -0.08047974109649658, 0.03372151032090187, -0.04058970510959625, 0.011458124034106731, 0.035233356058597565, 0.010580670088529587, -0.0176401250064373, -0.0037287373561412096, 0.016751417890191078, 0.04226100444793701, -0.016913652420043945, 0.014255552552640438, -0.0505790039896965, 0.028961509466171265, 0.011759106069803238, -0.02768619917333126, -0.03220440819859505, 0.03451642766594887, -0.005296703428030014, -0.04591591656208038, -0.004560523666441441, -0.04469611123204231, -5.7185501646017656e-05, -0.021578753367066383, -0.030068770051002502, 0.0028951475396752357, 0.034917254000902176, -0.019738251343369484, -0.056150466203689575, -0.010857722721993923, 0.009235871024429798, -0.07282893359661102, 0.012966274283826351, 0.004844042006880045, 0.03047022596001625, 0.01303629856556654, -0.00704015651717782, -0.05429763346910477, -0.03191782906651497, -0.014532000757753849, -0.009927071630954742, 0.05188412964344025, -0.012942450121045113, -1.9464014258119278e-05, -0.028560642153024673, -0.035566508769989014, -0.039553649723529816, -0.031193086877465248, 0.003959400579333305, -0.039357222616672516, 0.04611056298017502, 0.05621517077088356, -0.0005066735902801156, -0.014445994049310684, -0.003871720051392913, -0.011317885480821133, -0.010682611726224422, 0.04158286005258

In [28]:
def get_search_result(query,collection):

  get_knowledge=vector_search(query,collection)

  search_result=""

  for result in get_knowledge:
        search_result += f"Title: {result.get('title', 'N/A')}, Plot: {result.get('fullplot', 'N/A')}\n"

  return search_result

In [29]:

pipeline = [

    {
        "$vectorSearch": {
            "index": "vector_index",
            "queryVector": "query_embedding",
            "path": "embedding",
            "numCandidates": 150,  # Number of candidate matches to consider
            "limit": 4,  # Return top 4 matches
        }
    },
    {
        "$project": {
            "fullplot": 1,  # Include the plot field
            "title": 1,  # Include the title field
            "genres": 1,  # Include the genres field
            "score": {"$meta": "vectorSearchScore"},  # Include the search score
        }
    }
]

In [ ]:
print("The End")